### ISSUE TITLE
chatroom info

### ISSUE THREAD

**Issue by i4o** [go-task/examples#2]
I'd like to ask some questions  about go-task in chatroom, as it's probably proper channel for this kind of activity. At least that's what was kindly suggested by Andrey Nering.
I cannot find any instruction about the name of chatroom, or type of chat in README file. Maybe it's not obvious, but there are quite a few options and I'm undoubtedly not the most skilled in finding this info. 
Your help would be greatly appreciated. Do you talk IRC, slack or some other modern technology? What's the channel name and so on...

Thank you for your time,

**Comment by andreynering** [comment]
Sorry. In fact, the README is not clear about it. There's just a badge at the top.

[This is the link to the Slack room](https://gophers.slack.com/messages/task). If you don't have an account, you can create one with [this invite link](https://invite.slack.golangbridge.org/).
